/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    Landing: typeof import('./src/components/Landing.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
  }
}
